Updated CONTRIBUTING.md
StarReach/Pluto-Web pull request #20
Opened 2024-03-16 13:53 UTC by Maghish

Updated CONTRIBUTING.md to run newly edited back-end and front-end. Just check if the steps are correct and if this can be improved then let me know (you can simply edit it on your own as well)

2024-03-16 14:18 UTC, NanotechPikachu requested changes
The review has been completed with a short note.

2024-03-16 14:18 UTC, NanotechPikachu commented on CONTRIBUTING.md
> +> If you intend to run the back-end server in Node.js then you need to run `npm run start` but before that back-end server needs to be complied to JavaScript as it's TypeScript, so run `npm run build
If you intend to run the back-end server in Node.js, then you need to run `npm run start`. But before that, the back-end needs to be compiled to JavaScript as it's TypeScript. So run `npm run build` and then.....

2024-03-16 14:25 UTC, NanotechPikachu approved these changes
All is well in my end

2024-03-24 15:02 UTC, ateebplayz approved these changes
LGTM!

2024-03-24 15:02 UTC, merged